pull_request_rules:
  - name: Automatic merge imgbot
    conditions:
      - "author=imgbot[bot]"
    actions:
      merge:
        method: merge
      delete_head_branch: {}
      
  - name: Automatic release note bot
    conditions:
      - "author=github-actions[bot]"
      - "files~=\/rn.[md|xml]"
    actions:
      merge:
        method: merge
      delete_head_branch: {}