languageCode: "en-us"
title: "NVIDIA Networking Documentation"
theme: "netDocs"
baseURL: "/"
relURLs: True
googleAnalytics: "G-HTM5Y02305"
#Book configuration
disablePathToLower: True
enableGitInfo: True
noChmod: True
enableRobotsTXT: True
disableKinds: ["RSS", "taxonomy", "term"]

Params:
  cl_latest: "cumulus-linux-58"
  netq_latest: "cumulus-netq-48"
  sonic_latest: "sonic-202012"
  nvue_latest: "nvue-reference"
  air_latest: "nvidia-air"

  #Syntax Highlighting
  pygmentsCodeFencesGuessSyntax: True
  pygmentsUseClasses: True

  showVisitedLinks: True

  # (Optional, default True) Show or hide table of contents globally
  # You can also specify this parameter per page in front matter
  BookShowToC: True

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  #BookMenuBundle= /menus

  # Set menu to render from Current top level section(product)
  BookCurrentSectionMenu: True

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  #BookSection: "CumulusLinux"

  # This value is duplicate of $link-color for making active link highlight in menu bundle mode
  # BookMenuBundleActiveLinkColor: \#004ed0

  # Include JS scripts in pages. Disabled by default.
  # - Keep side menu on same scroll position during navigation
  BookEnableJS: True

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo: "https://github.com/CumulusNetworks/docs"

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  BookEditPath: "edit/stage/content"

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat: "Jan 2, 2006"

markup:
  tableOfContents:
    endLevel: 4
    ordered: False
    startLevel: 1
  goldmark:
    renderer:
      unsafe: True