# From https://github.com/marketplace/actions/nightly-merge
name: 'Scheduled Merge - Weekend'

  # Cron syntax is 'Minute[0,59] Hour[0,23] Day-of-month[1,31] Month-of-year[1,12] Day-of-week[0,6 with 0=Sunday]
  # The following example runs only on Sundays at 1400 UTC (0900 EST, 0600 PST)

  # To enable, uncomment the entire 'on' stanza below. It is currently enabled to merge stage to master on Sundays at 1400 UTC.

on:
  schedule:
    - cron:  '0 14 * * 0'

jobs:
  nightly-merge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Auto Merge Stage into Master
      uses: CumulusNetworks/gh-action-nightly-merge@v1.2.6
      with:
        source_branch: 'stage'
        target_branch: 'master'
        user_name: Cumulus Docs Auto Merge
        user_email: ethernet.docs@nvidia.com

      env:
        GITHUB_TOKEN: ${{ secrets.STU_GITHUB_TOKEN }}
