name: 'Weekly Link Check'

on:
  schedule:
    # Run Mondays, 8:30am PDT/3:30pm UTC
    #- cron:  '30 15 * * 1'
    - cron:  '0 15 * * *'

jobs:
  weekly-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-blc

    - uses: actions/setup-node@v1
    - run: npm install broken-link-checker -g
    - run: set -o pipefail
    - run: blc https://stage.d1l3582pfvms7p.amplifyapp.com/ --exclude redis.io --exclude cyberciti.biz --exclude mellanox.com --exclude support.mellanox.com --exclude api.netq.cumulusnetworks.com --exclude ntp.org --exclude /search/ --exclude linkedin.com --exclude cfengine.com --exclude community.mellanox.com --exclude debian.org --exclude linuxconfig.org --exclude github.com --exclude linuxfoundation.org --exclude dell.com --exclude .pdf --exclude .xls --exclude cumulus-vx --exclude cumulus-rmp --exclude /rn/ --exclude vmware.com --exclude /cumulus-linux/ --exclude /cumulus-netq/ --exclude /cumulus-linux-36/Whats-New/Cumulus-Linux-3.6-Release-Notes/ -r  | awk '/Getting links/ {via_line=$0} /BROKEN/ {print "\n" via_line "\n\n" $0 }' | echo "${pipestatus[1]}"
